[adelpanel]
user  = adelpanel
group = adelpanel

listen = /run/php/adelpanel.sock
listen.owner = adelpanel
listen.group = adelpanel
listen.mode  = 0660

pm = dynamic
pm.max_children      = 50
pm.start_servers     = 20
pm.min_spare_servers = 10
pm.max_spare_servers = 30
request_terminate_timeout = 180s

php_admin_value[error_log]      = /var/log/php/adelpanel-error.log
php_admin_flag[log_errors]      = on
php_admin_value[display_errors] = Off
php_admin_value[open_basedir]   = /opt/adelpanel:/var/www:/tmp:/opt/backups:/proc:/sys:/etc/nginx:/etc/pure-ftpd:/var/log/nginx:/etc/letsencrypt:/root/.acme.sh
