#!/bin/bash
# AdelPanel — set_dns.sh
# Устанавливает DNS серверы напрямую через /etc/resolv.conf
set -euo pipefail

if [ $# -lt 1 ]; then echo "ERROR: no DNS servers provided"; exit 1; fi

# Снимаем immutable флаг если есть
chattr -i /etc/resolv.conf 2>/dev/null || true

# Создаём новый resolv.conf
{
    echo "# Generated by AdelPanel"
    for ip in "$@"; do
        echo "nameserver $ip"
    done
} > /etc/resolv.conf

echo "OK: DNS → $*"
